### ISSUE TITLE
Decorated windows like iOS simulator remain in every workspace

### ISSUE THREAD

**Issue by brianwk** [acsandmann/rift#140]
When going through workspaces,  windows like iOS Simulator remain in every workspace. Even though I have app rule that dictate that it should be in it's own workspace:

`  { app_id = "com.apple.iphonesimulator", workspace = 3 }, `

However if I go to any empty workspace I will see it there, and I suspect that in the non-empty ones it's simply behind the other windows.

It seems a lot of windows with decorations like iOS Simulator, Firefox, and Zen have some form of issue. For example, iOS Simulator also cannot "tile" properly like Firefox/Zen. 

Another application that is specifically like iOS Simulator and will not stay in one workspace is Brain.fm. This is a Electron app for a subscription music service for people with ADHD. But I think if the issue is resolved for Simulator, it will be resolved for Brain.fm too.

**Comment by dagrlx** [comment]
> When going through workspaces, windows like iOS Simulator remain in every workspace. Even though I have app rule that dictate that it should be in it's own workspace:
> 
> ` { app_id = "com.apple.iphonesimulator", workspace = 3 },`
> 
> However if I go to any empty workspace I will see it there, and I suspect that in the non-empty ones it's simply behind the other windows.
> 
> It seems a lot of windows with decorations like iOS Simulator, Firefox, and Zen have some form of issue. For example, iOS Simulator also cannot "tile" properly like Firefox/Zen.
> 
> Another application that is specifically like iOS Simulator and will not stay in one workspace is Brain.fm. This is a Electron app for a subscription music service for people with ADHD. But I think if the issue is resolved for Simulator, it will be resolved for Brain.fm too.

It happened to me today with two applications, one was Teams and I don't remember the other.

**Comment by acsandmann** [comment]
i truly don't understand how this is happening as i can't reproduce it locally. i have tried teams, zen, and firefox and experience no issues. could you maybe provide a scren recording?

**Comment by brianwk** [comment]
@acsandmann Are you on an Intel Mac or Apple Silicon?

There is already a video recording in the Zen browser issue I believe.

Also what version of Zen and Firefox?

**Comment by acsandmann** [comment]
i think the issue is on apple silicon apps update their window frame to the window server too fast. need to revert ax move/resize events. i just was using those because for me they were faster.

**Comment by brianwk** [comment]
Here is a video for this specific issue @acsandmann 

https://github.com/user-attachments/assets/f1ec9068-149a-4441-9d7e-53990bb5bcda

**Comment by brianwk** [comment]
Also the "Brain.fm player" window will get lost, and the only way I can get it back is to go to Window menu and select Center. The WM can't manage this window so I set it to Floating but it doesn't seem to work.

**Comment by acsandmann** [comment]
i think i fixed this

**Comment by brianwk** [comment]
Unfortunately not fixed

❯ grep brain private_dot_config/rift/config.toml
auto_focus_blacklist = ["com.electron.brain.fm", "app.zen-browser.zen", "com.apple.ScreenContinuity"]
  { app_id = "com.electron.brain.fm", workspace = 0, floating = true },

The window still persists across every virtual workspace.

**Comment by brianwk** [comment]
So it's a lot better for Simulator. But it still will occasionally pop up on the wrong workspace. It's hard to tell how many times it happens since it's usually behind the other windows, but sometimes does a peak a boo.

Brain.fm window always has to be Centered to make it visible using Window -> Center menu. The window basically gets completely lost. I think I may have had this issue with Aerospace too so would be nice to figure out a solution.

AutoRaise doesn't work at all for Brain.fm. Basically Brain.fm has the opposite issue. It doesn't show on ANY workspace. Maybe for some windows you have to fall back to using that "Center" function, although I'm unsure if you can do it programatically.

**Comment by acsandmann** [comment]
so the issue with this is that for whatever reason it fails when using setbatchwindowframe which tries to just set the systems enhanced ui to disabled and bulk window frame sets instead of setting each windows eui to false and doing work and then re-enabling so now we just queue a normal set frame whenever a window fails in batch. 

i dont really understand why they would fail because there is no good reason to so this is really a temporary fix/workaround. i will have to test with brain.fm but what i will say is these issues are a product of apps not doing things properly and disobeying macos rules but of course we must handle these cases.

**Comment by acsandmann** [comment]
```
diff --git a/src/actor/app.rs b/src/actor/app.rs
index 658ed72..d184a47 100644
--- a/src/actor/app.rs
+++ b/src/actor/app.rs
@@ -637,7 +637,7 @@ impl State {
                 ));
             }
             &mut Request::SetBatchWindowFrame(ref mut frames, txid) => {
-                unsafe { SLSDisableUpdate(*G_CONNECTION) };
+                /*unsafe { SLSDisableUpdate(*G_CONNECTION) };
                 let result = with_system_enhanced_ui_disabled(|| -> Result<(), AxError> {
                     for (wid, desired) in frames.iter() {
                         let elem = match self.window_mut(*wid) {
@@ -685,7 +685,12 @@ impl State {
                 unsafe { SLSReenableUpdate(*G_CONNECTION) };
                 if let Err(err) = result {
                     return Err(err);
-                }
+                }*/
+                self.handle.as_ref().map(|h| {
+                    for (wid, desired) in frames.iter() {
+                        let _ = h.send(Request::SetWindowFrame(*wid, *desired, txid, true));
+                    }
+                });
             }
             &mut Request::BeginWindowAnimation(wid) => {
                 let window = self.window(wid)?;
```


let me know if this patch helps at all. also with the zenbrowser issue. also just in general, is it faster/slower/??

**Comment by brianwk** [comment]
> ```
> diff --git a/src/actor/app.rs b/src/actor/app.rs
> index 658ed72..d184a47 100644
> --- a/src/actor/app.rs
> +++ b/src/actor/app.rs
> @@ -637,7 +637,7 @@ impl State {
>                  ));
>              }
>              &mut Request::SetBatchWindowFrame(ref mut frames, txid) => {
> -                unsafe { SLSDisableUpdate(*G_CONNECTION) };
> +                /*unsafe { SLSDisableUpdate(*G_CONNECTION) };
>                  let result = with_system_enhanced_ui_disabled(|| -> Result<(), AxError> {
>                      for (wid, desired) in frames.iter() {
>                          let elem = match self.window_mut(*wid) {
> @@ -685,7 +685,12 @@ impl State {
>                  unsafe { SLSReenableUpdate(*G_CONNECTION) };
>                  if let Err(err) = result {
>                      return Err(err);
> -                }
> +                }*/
> +                self.handle.as_ref().map(|h| {
> +                    for (wid, desired) in frames.iter() {
> +                        let _ = h.send(Request::SetWindowFrame(*wid, *desired, txid, true));
> +                    }
> +                });
>              }
>              &mut Request::BeginWindowAnimation(wid) => {
>                  let window = self.window(wid)?;
> ```
> 
> let me know if this patch helps at all. also with the zenbrowser issue. also just in general, is it faster/slower/??

do you want me to apply this patch?

**Comment by acsandmann** [comment]
nah its now outdated. just see if main is better since i can't reproduce the zen issue regardless of what i do. this should fix the simulator issue though

**Comment by brianwk** [comment]
> nah its now outdated. just see if main is better since i can't reproduce the zen issue regardless of what i do. this should fix the simulator issue though

Seems the solution is from my side is "Get good" 😆

**Comment by brianwk** [comment]
> nah its now outdated. just see if main is better since i can't reproduce the zen issue regardless of what i do. this should fix the simulator issue though

Simulator issue isn't fixed on latest main. Window still shows up on work spaces it isn't assigned to; it's explicitly assigned to workspace 3. It does show up on workspace 3 but it will pop up on work spaces it shouldn't be on.

It also doesn't tile correctly because you probably need to determine the "max width" of the simulator window since you can't really make it as wide as other windows due to how tall the window is.

**Comment by acsandmann** [comment]
it is no longer occuring for me..
