### ISSUE TITLE
Minimising some windows doesn't give the reserved space free for the other windows

### ISSUE THREAD

**Issue by itouchdennis** [acsandmann/rift#191]
Steps to reproduce:
- Open 1 App, e.g. Safari
- Open another App that triggers the bug (Apps I found out that are affected are Telegram or Kitty terminal, Finder or Safari aren't affected and some working but others not)
- Trigger minimise, either cmd + w or via decoration bar of the app

See screenshot: (Kitty was opened and minimised, if I close the app entire, safari will become the reserved space from kitty)

<img width="1728" height="1081" alt="Image" src="https://github.com/user-attachments/assets/3ca16da2-7d3a-4e57-af13-9e00fcedc77e" />

**Comment by acsandmann** [comment]
i am not on macos tahoe but i cannot reproduce this with kitty (nor any other app) on sequoia. the fact that it only happens with kitty makes me feel like it is a bug on their side, not ours. also, iirc, kitty has had bugs in the past where it didn't send the right events so that probably makes me lean even further to the fact that its on their end.

**Comment by itouchdennis** [comment]
Yes, its tahoe, this might be an issue here aswell.
I will watch for further apps, currently I got besides kitty also the "telegram messenger" app, or the "better touch tool" app, which got the same behavior as kitty. 

While other apps like "MS Visual Studio Code" are working as expected when minimized.

I havn't that much apps currently on this macbook. Its not a dealbreaker I just close the apps entirely if there is a bugged space in here but it takes a bit of the "illusion" of having a native tiling that actually works great on tahoe (while I still think rift is the best tiling package we have on mac which isn't invasive and working on tahoe)

**Comment by acsandmann** [comment]
i think it *should* ideally also end up retiling when you switch away and then back to the workspace as it requeries all of the windows in the workspace and then will see that one has been minimized. but, we do listen to the minimize event given to us by apple, and there is not that much that can be done aside from that to be honest.. 


edit: i just tried both telegram and btt and those work fine for me so this must be a tahoe issue somehow...

**Comment by itouchdennis** [comment]
Ty for the clearance!
Usually I don't minimize apps, usually I close them, so I think I'll remove the minimize shortcut and never face the issue that some apps has on macos again 

Edit aswell:

For sure it might be tahoe, that thing broke a lot as far as I've read even from other projects....

**Comment by AKarbas** [comment]
I also see this still — only commenting as I minimize via Cmd+M not Cmd+W that the OP mentions.

**Comment by brianwk** [comment]
Hello

I'm also seeing this, where the window is the only window on a workspace, but then it has an empty space as though there's a window tiled there. When I do a `rift-cli query windows` it only shows the 1 window as well. Quite a strange bug. The common denominator is that it involves a minimized (hidden) app. If I can actually figure out what window it is, I'm able to resolve the issue. 

Also I'm on Sequoia Apple Silicon, not Tahoe. I've been avoiding upgrading!

Another app that causes this is Spotify.

**Comment by acsandmann** [comment]
is this resolved on main? i pushed out a fix

**Comment by itouchdennis** [comment]
Its not resolved for me: 
Tried telegram and kitty.
Telegram minimized, the other window got the free space, bringing it back up moves telegram in background, existing window don't tile in half again

<img width="1728" height="1117" alt="Image" src="https://github.com/user-attachments/assets/f08ade0b-0c57-40d4-a634-f1d34a3338fd" />

Also tried it with e.g. 2 kitty terminals 
minimized 1 with cmd + w, leads to the same behavior as before, into an empty tiling space:


<img width="1728" height="1117" alt="Image" src="https://github.com/user-attachments/assets/20bc5c02-d2f1-41ba-a9b9-1094413e2c04" />
(left was a kitty windows, which is now minimized)

**Comment by brianwk** [comment]
Now that I recall, it also happened to me with WezTerm, it happens when an app has more than one window a lot it seems.
