### ISSUE TITLE
Joining 2 windows into one causes Rift to stop managing windows

### ISSUE THREAD

**Issue by brianwk** [acsandmann/rift#206]
Even if I press the hotkey to activate Rift, it still no longer manages windows.

Steps to reproduce:
- Have four windows: Simulator, 3 x wezterm
- Tiled side by side. Join one of the WezTerm windows using the right join direction. Then join the two windows already joined into one window using the right join direction.

Rift will stop responding after this, and you have to CTRL+C and restart Rift. 

You are able to join three windows together, but I was only able to do it using up / down direction. I am only using one display currently.

As soon as I join the two windows, the Simulator window width grows in Rift's state and the tiling has a gap again. On initialization it tiles perfect now.

**Comment by acsandmann** [comment]
@brianwk can you confirm that this is fixed on main?

**Comment by brianwk** [comment]
@acsandmann it's fixed, my path got messed up apparently.

not fixed: Tiling messes up when i join the windows

**Comment by acsandmann** [comment]
https://github.com/user-attachments/assets/b4585cb6-35b0-4c7c-b4e2-a90590cd3e82

i cant repro anymore

**Comment by brianwk** [comment]
@acsandmann Joining windows works now, but it still messes up the tiling when you join the windows. 

Basically I have SImulator and three wezterm windows, simulator is tiled perfectly to the side. Then I join the windows and the gap appears.

**Comment by acsandmann** [comment]
oh, that is just the pre existing issue...

<details>
  <summary>this patch might make that a little better though...</summary>
@brianwk this should fix all of your issues with ios simulator taking up more space than it actually takes up.  

```patch
diff --git a/src/actor/reactor.rs b/src/actor/reactor.rs
index 1439b33..82ac99d 100644
--- a/src/actor/reactor.rs
+++ b/src/actor/reactor.rs
@@ -413,6 +413,7 @@ struct WindowState {
     is_ax_standard: bool,
     is_ax_root: bool,
     is_minimized: bool,
+    is_resizable: bool,
     is_manageable: bool,
     window_server_id: Option<WindowServerId>,
     #[allow(unused)]
@@ -431,6 +432,7 @@ impl From<WindowInfo> for WindowState {
             is_ax_standard: info.is_standard,
             is_ax_root: info.is_root,
             is_minimized: info.is_minimized,
+            is_resizable: info.is_resizable,
             is_manageable: false,
             window_server_id: info.sys_id,
             bundle_id: info.bundle_id,
diff --git a/src/actor/reactor/animation.rs b/src/actor/reactor/animation.rs
index c046019..7a8e667 100644
--- a/src/actor/reactor/animation.rs
+++ b/src/actor/reactor/animation.rs
@@ -142,6 +142,19 @@ fn ease(t: f64) -> f64 {
 
 fn blend(a: f64, b: f64, s: f64) -> f64 { (1.0 - s) * a + s * b }
 
+fn clamp_origin_to_rect(origin: CGPoint, size: CGSize, container: CGRect) -> CGPoint {
+    let min = container.min();
+    let max = container.max();
+    let max_x = (max.x - size.width).max(min.x);
+    let max_y = (max.y - size.height).max(min.y);
+    CGPoint::new(origin.x.clamp(min.x, max_x), origin.y.clamp(min.y, max_y))
+}
+
+fn fixed_target(target: CGRect, size: CGSize) -> CGRect {
+    let origin = clamp_origin_to_rect(target.origin, size, target);
+    CGRect::new(origin, size)
+}
+
 pub struct AnimationManager;
 
 impl AnimationManager {
@@ -164,7 +177,7 @@ impl AnimationManager {
         let mut animated_wids_wsids: Vec<u32> = Vec::new();
         let mut any_frame_changed = false;
 
-        for &(wid, target_frame) in layout {
+        for &(wid, raw_target_frame) in layout {
             // Skip applying layout frames and animations for the window currently being dragged.
             if skip_wid == Some(wid) {
                 trace!(
@@ -174,18 +187,31 @@ impl AnimationManager {
                 continue;
             }
 
-            let target_frame = target_frame.round();
-            let (current_frame, window_server_id, txid) =
-                match reactor.window_manager.windows.get_mut(&wid) {
+            let target_frame = raw_target_frame.round();
+            let (current_frame, window_server_id, txid, is_resizable, target_frame) =
+                match reactor.window_manager.windows.get(&wid) {
                     Some(window) => {
                         let current_frame = window.frame_monotonic;
+                        let constraint = reactor.layout_manager.layout_engine.window_constraint(wid);
+                        let is_resizable =
+                            constraint.map(|c| c.is_resizable).unwrap_or(window.is_resizable);
+                        let size_for_fixed =
+                            constraint.map(|c| c.size).unwrap_or(current_frame.size);
+                        let target_frame =
+                            if is_resizable { target_frame } else { fixed_target(target_frame, size_for_fixed) };
                         if target_frame.same_as(current_frame) {
                             continue;
                         }
                         any_frame_changed = true;
                         let wsid = window.window_server_id.unwrap();
                         let txid = reactor.transaction_manager.generate_next_txid(wsid);
-                        (current_frame, Some(wsid), txid)
+                        (
+                            current_frame,
+                            Some(wsid),
+                            txid,
+                            is_resizable,
+                            target_frame,
+                        )
                     }
                     None => {
                         debug!(?wid, "Skipping - window no longer exists");
@@ -208,8 +234,30 @@ impl AnimationManager {
             if is_active {
                 trace!(?wid, ?current_frame, ?target_frame, "Animating visible window");
                 animated_wids_wsids.push(wid.idx.into());
-                anim.add_window(&app_state.handle, wid, current_frame, target_frame, false, txid);
-                animated_count += 1;
+                if is_resizable {
+                    anim.add_window(
+                        &app_state.handle,
+                        wid,
+                        current_frame,
+                        target_frame,
+                        false,
+                        txid,
+                    );
+                    animated_count += 1;
+                } else {
+                    if let Err(e) = app_state.handle.send(Request::SetWindowPos(
+                        wid,
+                        target_frame.origin,
+                        txid,
+                        true,
+                    )) {
+                        debug!(
+                            ?wid,
+                            ?e,
+                            "Failed to send position request for non-resizable window"
+                        );
+                    }
+                }
                 if let Some(wsid) = window_server_id {
                     reactor.transaction_manager.update_txid_entries([(wsid, txid, target_frame)]);
                 }
@@ -223,9 +271,17 @@ impl AnimationManager {
                 if let Some(wsid) = window_server_id {
                     reactor.transaction_manager.update_txid_entries([(wsid, txid, target_frame)]);
                 }
-                if let Err(e) =
+                let send_result = if is_resizable {
                     app_state.handle.send(Request::SetWindowFrame(wid, target_frame, txid, true))
-                {
+                } else {
+                    app_state.handle.send(Request::SetWindowPos(
+                        wid,
+                        target_frame.origin,
+                        txid,
+                        true,
+                    ))
+                };
+                if let Err(e) = send_result {
                     debug!(?wid, ?e, "Failed to send frame request for hidden window");
                     continue;
                 }
@@ -253,10 +309,10 @@ impl AnimationManager {
         layout: &[(WindowId, CGRect)],
         skip_wid: Option<WindowId>,
     ) -> bool {
-        let mut per_app: HashMap<pid_t, Vec<(WindowId, CGRect)>> = HashMap::default();
+        let mut per_app: HashMap<pid_t, Vec<(WindowId, CGRect, bool)>> = HashMap::default();
         let mut any_frame_changed = false;
 
-        for &(wid, target_frame) in layout {
+        for &(wid, raw_target_frame) in layout {
             // Skip applying a layout frame for the window currently being dragged.
             if skip_wid == Some(wid) {
                 trace!(?wid, "Skipping layout update for window currently being dragged");
@@ -267,7 +323,16 @@ impl AnimationManager {
                 debug!(?wid, "Skipping layout - window no longer exists");
                 continue;
             };
-            let target_frame = target_frame.round();
+            let target_frame = raw_target_frame.round();
+            let constraint = reactor.layout_manager.layout_engine.window_constraint(wid);
+            let is_resizable =
+                constraint.map(|c| c.is_resizable).unwrap_or(window.is_resizable);
+            let fixed_size = constraint.map(|c| c.size).unwrap_or(window.frame_monotonic.size);
+            let target_frame = if is_resizable {
+                target_frame
+            } else {
+                fixed_target(target_frame, fixed_size)
+            };
             let current_frame = window.frame_monotonic;
             if target_frame.same_as(current_frame) {
                 continue;
@@ -280,7 +345,7 @@ impl AnimationManager {
                 "Instant workspace positioning"
             );
 
-            per_app.entry(wid.pid).or_default().push((wid, target_frame));
+            per_app.entry(wid.pid).or_default().push((wid, target_frame, is_resizable));
         }
 
         for (pid, frames) in per_app.into_iter() {
@@ -295,7 +360,7 @@ impl AnimationManager {
 
             let handle = app_state.handle.clone();
 
-            let (first_wid, first_target) = frames[0];
+            let (first_wid, first_target, _) = frames[0];
             let mut txid = TransactionId::default();
             let mut has_txid = false;
             let mut txid_entries: Vec<(WindowServerId, TransactionId, CGRect)> = Vec::new();
@@ -308,7 +373,7 @@ impl AnimationManager {
             }
 
             if has_txid {
-                for (wid, frame) in frames.iter().skip(1) {
+                for (wid, frame, _) in frames.iter().skip(1) {
                     if let Some(w) = reactor.window_manager.windows.get_mut(wid) {
                         if let Some(wsid) = w.window_server_id {
                             reactor.transaction_manager.set_last_sent_txid(wsid, txid);
@@ -319,17 +384,42 @@ impl AnimationManager {
                 reactor.transaction_manager.update_txid_entries(txid_entries);
             }
 
-            let frames_to_send = frames.clone();
-            if let Err(e) = handle.send(Request::SetBatchWindowFrame(frames_to_send, txid)) {
-                debug!(
-                    ?pid,
-                    ?e,
-                    "Failed to send batch frame request - app may have quit"
-                );
-                continue;
+            let mut resizable_frames: Vec<(WindowId, CGRect)> = Vec::new();
+            let mut pos_only: Vec<(WindowId, CGRect)> = Vec::new();
+            for (wid, frame, is_resizable) in frames {
+                if is_resizable {
+                    resizable_frames.push((wid, frame));
+                } else {
+                    pos_only.push((wid, frame));
+                }
+            }
+
+            if !resizable_frames.is_empty() {
+                if let Err(e) =
+                    handle.send(Request::SetBatchWindowFrame(resizable_frames.clone(), txid))
+                {
+                    debug!(
+                        ?pid,
+                        ?e,
+                        "Failed to send batch frame request - app may have quit"
+                    );
+                }
+            }
+
+            for (wid, frame) in pos_only {
+                if let Err(e) = handle.send(Request::SetWindowPos(wid, frame.origin, txid, true)) {
+                    debug!(
+                        ?wid,
+                        ?e,
+                        "Failed to send position request for non-resizable window"
+                    );
+                }
+                if let Some(window) = reactor.window_manager.windows.get_mut(&wid) {
+                    window.frame_monotonic = frame;
+                }
             }
 
-            for (wid, target_frame) in &frames {
+            for (wid, target_frame) in &resizable_frames {
                 if let Some(window) = reactor.window_manager.windows.get_mut(wid) {
                     window.frame_monotonic = *target_frame;
                 }
diff --git a/src/actor/reactor/events/command.rs b/src/actor/reactor/events/command.rs
index 86a26ca..ab13b38 100644
--- a/src/actor/reactor/events/command.rs
+++ b/src/actor/reactor/events/command.rs
@@ -334,14 +334,14 @@ impl CommandEventHandler {
             return;
         };
 
-        let (window_server_id, window_frame) = match reactor.window_manager.windows.get(&window_id)
-        {
-            Some(state) => (state.window_server_id, state.frame_monotonic),
-            None => {
-                warn!(?window_id, "Move window to display ignored: unknown window");
-                return;
-            }
-        };
+        let (window_server_id, window_frame, is_resizable) =
+            match reactor.window_manager.windows.get(&window_id) {
+                Some(state) => (state.window_server_id, state.frame_monotonic, state.is_resizable),
+                None => {
+                    warn!(?window_id, "Move window to display ignored: unknown window");
+                    return;
+                }
+            };
 
         let Some(source_space) = reactor.best_space_for_window(&window_frame, window_server_id)
         else {
@@ -394,20 +394,38 @@ impl CommandEventHandler {
             if let Some(wsid) = window_server_id {
                 let txid = reactor.transaction_manager.generate_next_txid(wsid);
                 reactor.transaction_manager.set_last_sent_txid(wsid, txid);
-                let _ = app.handle.send(crate::actor::app::Request::SetWindowFrame(
-                    window_id,
-                    target_frame,
-                    txid,
-                    true,
-                ));
+                let _ = if is_resizable {
+                    app.handle.send(crate::actor::app::Request::SetWindowFrame(
+                        window_id,
+                        target_frame,
+                        txid,
+                        true,
+                    ))
+                } else {
+                    app.handle.send(crate::actor::app::Request::SetWindowPos(
+                        window_id,
+                        target_frame.origin,
+                        txid,
+                        true,
+                    ))
+                };
             } else {
                 let txid = TransactionId::default();
-                let _ = app.handle.send(crate::actor::app::Request::SetWindowFrame(
-                    window_id,
-                    target_frame,
-                    txid,
-                    true,
-                ));
+                let _ = if is_resizable {
+                    app.handle.send(crate::actor::app::Request::SetWindowFrame(
+                        window_id,
+                        target_frame,
+                        txid,
+                        true,
+                    ))
+                } else {
+                    app.handle.send(crate::actor::app::Request::SetWindowPos(
+                        window_id,
+                        target_frame.origin,
+                        txid,
+                        true,
+                    ))
+                };
             }
         }
 
diff --git a/src/actor/reactor/events/window_discovery.rs b/src/actor/reactor/events/window_discovery.rs
index 48f23f8..7d6d7ab 100644
--- a/src/actor/reactor/events/window_discovery.rs
+++ b/src/actor/reactor/events/window_discovery.rs
@@ -234,6 +234,7 @@ impl WindowDiscoveryHandler {
                         existing.is_ax_standard = info.is_standard;
                         existing.is_ax_root = info.is_root;
                         existing.is_minimized = info.is_minimized;
+                        existing.is_resizable = info.is_resizable;
                         existing.window_server_id = info.sys_id;
                         existing.bundle_id = info.bundle_id.clone();
                         existing.bundle_path = info.path.clone();
@@ -248,6 +249,7 @@ impl WindowDiscoveryHandler {
                         is_ax_standard: info.is_standard,
                         is_ax_root: info.is_root,
                         is_minimized: info.is_minimized,
+                        is_resizable: info.is_resizable,
                         is_manageable: false,
                         window_server_id: info.sys_id,
                         bundle_id: info.bundle_id.clone(),
diff --git a/src/actor/reactor/managers.rs b/src/actor/reactor/managers.rs
index 2c6dfdf..c01a4d2 100644
--- a/src/actor/reactor/managers.rs
+++ b/src/actor/reactor/managers.rs
@@ -18,7 +18,7 @@ use crate::actor::reactor::animation::AnimationManager;
 use crate::actor::{event_tap, menu_bar, raise_manager, stack_line, window_notify, wm_controller};
 use crate::common::collections::{HashMap, HashSet};
 use crate::common::config::{Config, WindowSnappingSettings};
-use crate::layout_engine::LayoutEngine;
+use crate::layout_engine::{LayoutEngine, WindowConstraint};
 use crate::sys::screen::{ScreenId, SpaceId};
 use crate::sys::window_server::{WindowServerId, WindowServerInfo};
 
@@ -213,6 +213,82 @@ impl LayoutManager {
 
     fn calculate_layout(reactor: &mut Reactor) -> LayoutResult {
         let screens = reactor.space_manager.screens.clone();
+        let constraints: HashMap<WindowId, WindowConstraint> = reactor
+            .window_manager
+            .windows
+            .iter()
+            .map(|(wid, window)| {
+                let sls_constraints = window
+                    .window_server_id
+                    .and_then(|wsid| crate::sys::window_server::window_constraints(wsid));
+                let (size, is_resizable) = if let Some(c) = sls_constraints {
+                    // Clamp to SLS min/max when they look sane (<100k) and fall back to current frame.
+                    let mut adjusted = window.frame_monotonic.size;
+                    let min_w = if c.min.width > 0.0 {
+                        Some(c.min.width)
+                    } else {
+                        None
+                    };
+                    let min_h = if c.min.height > 0.0 {
+                        Some(c.min.height)
+                    } else {
+                        None
+                    };
+                    let max_w = if c.max.width.is_finite()
+                        && c.max.width > 0.0
+                        && c.max.width < 100_000.0
+                    {
+                        Some(c.max.width)
+                    } else {
+                        None
+                    };
+                    let max_h = if c.max.height.is_finite()
+                        && c.max.height > 0.0
+                        && c.max.height < 100_000.0
+                    {
+                        Some(c.max.height)
+                    } else {
+                        None
+                    };
+
+                    if let Some(w) = min_w {
+                        adjusted.width = adjusted.width.max(w);
+                    }
+                    if let Some(h) = min_h {
+                        adjusted.height = adjusted.height.max(h);
+                    }
+                    if let Some(w) = max_w {
+                        adjusted.width = adjusted.width.min(w);
+                    }
+                    if let Some(h) = max_h {
+                        adjusted.height = adjusted.height.min(h);
+                    }
+
+                    // If SLS reports effectively fixed bounds, treat window as non-resizable even
+                    // when AX thinks otherwise so our tiling respects the cap.
+                    let fixed_width = match (min_w, max_w) {
+                        (Some(min), Some(max)) => (max - min).abs() < 1.0,
+                        _ => false,
+                    };
+                    let fixed_height = match (min_h, max_h) {
+                        (Some(min), Some(max)) => (max - min).abs() < 1.0,
+                        _ => false,
+                    };
+                    let sls_says_fixed = fixed_width && fixed_height;
+
+                    (adjusted, window.is_resizable && !sls_says_fixed)
+                } else {
+                    (window.frame_monotonic.size, window.is_resizable)
+                };
+                (*wid, WindowConstraint { size, is_resizable })
+            })
+            .collect();
+        for (wid, constraint) in &constraints {
+            if let Some(window) = reactor.window_manager.windows.get_mut(wid) {
+                window.is_resizable = constraint.is_resizable;
+            }
+        }
+        reactor.layout_manager.layout_engine.set_window_constraints(constraints);
         let mut layout_result = LayoutResult::new();
 
         for screen in screens {
@@ -245,6 +321,18 @@ impl LayoutManager {
                     reactor.config_manager.config.settings.ui.stack_line.vert_placement,
                     |wid| reactor.window_manager.windows.get(&wid).map(|w| w.frame_monotonic),
                 );
+            let layout = layout
+                .into_iter()
+                .map(|(wid, rect)| {
+                    if let Some(window) = reactor.window_manager.windows.get(&wid) {
+                        if !window.is_resizable {
+                            let size = window.frame_monotonic.size;
+                            return (wid, CGRect::new(rect.origin, size));
+                        }
+                    }
+                    (wid, rect)
+                })
+                .collect();
             layout_result.push((space, layout));
         }
 
diff --git a/src/actor/reactor/testing.rs b/src/actor/reactor/testing.rs
index c8ee956..987d19b 100644
--- a/src/actor/reactor/testing.rs
+++ b/src/actor/reactor/testing.rs
@@ -83,6 +83,7 @@ pub fn make_window(idx: usize) -> WindowInfo {
         is_standard: true,
         is_root: true,
         is_minimized: false,
+        is_resizable: true,
         title: format!("Window{idx}"),
         frame: CGRect::new(
             CGPoint::new(100.0 * f64::from(idx as u32), 100.0),
diff --git a/src/actor/reactor/tests.rs b/src/actor/reactor/tests.rs
index f210c4b..30845fa 100644
--- a/src/actor/reactor/tests.rs
+++ b/src/actor/reactor/tests.rs
@@ -436,6 +436,7 @@ fn it_retains_windows_without_server_ids_after_login_visibility_failure() {
         is_standard: true,
         is_root: true,
         is_minimized: false,
+        is_resizable: true,
         title: "NoServerId".to_string(),
         frame: CGRect::new(CGPoint::new(50., 50.), CGSize::new(400., 400.)),
         sys_id: None,
@@ -536,6 +537,7 @@ fn it_respects_wsid_suppression_for_apply_app_rules() {
         is_standard: true,
         is_root: true,
         is_minimized: false,
+        is_resizable: true,
         title: "NoServerId".to_string(),
         frame: CGRect::new(CGPoint::new(50., 50.), CGSize::new(400., 400.)),
         sys_id: None,
@@ -551,6 +553,7 @@ fn it_respects_wsid_suppression_for_apply_app_rules() {
         is_ax_standard: info.is_standard,
         is_ax_root: info.is_root,
         is_minimized: info.is_minimized,
+        is_resizable: info.is_resizable,
         is_manageable: true,
         window_server_id: info.sys_id,
         bundle_id: info.bundle_id.clone(),
diff --git a/src/layout_engine.rs b/src/layout_engine.rs
index c3878f0..3edd16c 100644
--- a/src/layout_engine.rs
+++ b/src/layout_engine.rs
@@ -5,7 +5,7 @@ pub mod systems;
 pub mod utils;
 mod workspaces;
 
-pub use engine::{EventResponse, LayoutCommand, LayoutEngine, LayoutEvent};
+pub use engine::{EventResponse, LayoutCommand, LayoutEngine, LayoutEvent, WindowConstraint};
 pub(crate) use floating::FloatingManager;
 pub use graph::{Direction, LayoutKind, Orientation};
 pub(crate) use systems::LayoutId;
diff --git a/src/layout_engine/engine.rs b/src/layout_engine/engine.rs
index b4fdc65..6b7233c 100644
--- a/src/layout_engine/engine.rs
+++ b/src/layout_engine/engine.rs
@@ -14,8 +14,16 @@ use crate::common::collections::HashMap;
 use crate::common::config::LayoutSettings;
 use crate::layout_engine::LayoutSystem;
 use crate::model::{VirtualWorkspaceId, VirtualWorkspaceManager};
+use crate::sys::geometry::CGSizeDef;
 use crate::sys::screen::SpaceId;
 
+#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq)]
+pub struct WindowConstraint {
+    #[serde(with = "CGSizeDef")]
+    pub size: CGSize,
+    pub is_resizable: bool,
+}
+
 #[derive(Debug, Clone)]
 pub struct GroupContainerInfo {
     pub node_id: crate::model::tree::NodeId,
@@ -109,6 +117,8 @@ pub struct LayoutEngine {
     space_display_map: HashMap<SpaceId, Option<String>>,
     #[serde(skip)]
     display_last_space: HashMap<String, SpaceId>,
+    #[serde(default)]
+    window_constraints: HashMap<WindowId, WindowConstraint>,
 }
 
 impl LayoutEngine {
@@ -116,6 +126,15 @@ impl LayoutEngine {
         self.layout_settings = settings.clone();
     }
 
+    pub fn set_window_constraints(&mut self, constraints: HashMap<WindowId, WindowConstraint>) {
+        self.window_constraints = constraints;
+        self.tree.set_window_constraints(&self.window_constraints);
+    }
+
+    pub fn window_constraint(&self, wid: WindowId) -> Option<&WindowConstraint> {
+        self.window_constraints.get(&wid)
+    }
+
     pub fn update_virtual_workspace_settings(
         &mut self,
         settings: &crate::common::config::VirtualWorkspaceSettings,
@@ -558,6 +577,7 @@ impl LayoutEngine {
             broadcast_tx,
             space_display_map: HashMap::default(),
             display_last_space: HashMap::default(),
+            window_constraints: HashMap::default(),
         }
     }
 
@@ -1115,6 +1135,7 @@ impl LayoutEngine {
         stack_line_horiz: crate::common::config::HorizontalPlacement,
         stack_line_vert: crate::common::config::VerticalPlacement,
     ) -> Vec<(WindowId, CGRect)> {
+        self.tree.set_window_constraints(&self.window_constraints);
         let layout = self.layout(space);
         self.tree.calculate_layout(
             layout,
@@ -1140,6 +1161,7 @@ impl LayoutEngine {
     where
         F: Fn(WindowId) -> Option<CGRect>,
     {
+        self.tree.set_window_constraints(&self.window_constraints);
         use crate::model::HideCorner;
 
         let mut positions = HashMap::default();
@@ -1311,7 +1333,7 @@ impl LayoutEngine {
     }
 
     pub fn calculate_layout_for_workspace(
-        &self,
+        &mut self,
         space: SpaceId,
         workspace_id: crate::model::VirtualWorkspaceId,
         screen: CGRect,
@@ -1320,6 +1342,7 @@ impl LayoutEngine {
         stack_line_horiz: crate::common::config::HorizontalPlacement,
         stack_line_vert: crate::common::config::VerticalPlacement,
     ) -> Vec<(WindowId, CGRect)> {
+        self.tree.set_window_constraints(&self.window_constraints);
         let mut positions = HashMap::default();
 
         if let Some(layout) = self.workspace_layouts.active(space, workspace_id) {
diff --git a/src/layout_engine/systems.rs b/src/layout_engine/systems.rs
index bb4fac3..4aa20fa 100644
--- a/src/layout_engine/systems.rs
+++ b/src/layout_engine/systems.rs
@@ -3,7 +3,8 @@ use objc2_core_foundation::CGRect;
 use serde::{Deserialize, Serialize};
 
 use crate::actor::app::{WindowId, pid_t};
-use crate::layout_engine::{Direction, LayoutKind};
+use crate::common::collections::HashMap;
+use crate::layout_engine::{Direction, LayoutKind, WindowConstraint};
 
 slotmap::new_key_type! { pub struct LayoutId; }
 
@@ -12,6 +13,7 @@ pub trait LayoutSystem: Serialize + for<'de> Deserialize<'de> {
     fn create_layout(&mut self) -> LayoutId;
     fn clone_layout(&mut self, layout: LayoutId) -> LayoutId;
     fn remove_layout(&mut self, layout: LayoutId);
+    fn set_window_constraints(&mut self, constraints: &HashMap<WindowId, WindowConstraint>);
 
     fn draw_tree(&self, layout: LayoutId) -> String;
 
diff --git a/src/layout_engine/systems/bsp.rs b/src/layout_engine/systems/bsp.rs
index 29b897c..cf10ac8 100644
--- a/src/layout_engine/systems/bsp.rs
+++ b/src/layout_engine/systems/bsp.rs
@@ -5,7 +5,7 @@ use crate::actor::app::{WindowId, pid_t};
 use crate::common::collections::{HashMap, HashSet};
 use crate::layout_engine::systems::LayoutSystem;
 use crate::layout_engine::utils::compute_tiling_area;
-use crate::layout_engine::{Direction, LayoutId, LayoutKind, Orientation};
+use crate::layout_engine::{Direction, LayoutId, LayoutKind, Orientation, WindowConstraint};
 use crate::model::selection::*;
 use crate::model::tree::{NodeId, NodeMap, Tree};
 
@@ -34,6 +34,8 @@ pub struct BspLayoutSystem {
     tree: Tree<Components>,
     kind: slotmap::SecondaryMap<NodeId, NodeKind>,
     window_to_node: HashMap<WindowId, NodeId>,
+    #[serde(skip)]
+    window_constraints: HashMap<WindowId, WindowConstraint>,
 }
 
 impl BspLayoutSystem {
@@ -182,6 +184,7 @@ impl Default for BspLayoutSystem {
             tree: Tree::with_observer(Components::default()),
             kind: Default::default(),
             window_to_node: Default::default(),
+            window_constraints: Default::default(),
         }
     }
 }
@@ -201,6 +204,13 @@ impl BspLayoutSystem {
         id
     }
 
+    fn constraint_for_node(&self, node: NodeId) -> Option<&WindowConstraint> {
+        match self.kind.get(node) {
+            Some(NodeKind::Leaf { window: Some(w), .. }) => self.window_constraints.get(w),
+            _ => None,
+        }
+    }
+
     fn descend_to_leaf(&self, mut node: NodeId) -> NodeId {
         loop {
             match self.kind.get(node) {
@@ -399,13 +409,22 @@ impl BspLayoutSystem {
                 ..
             }) => {
                 if let Some(w) = window {
-                    let target = if *fullscreen {
+                    let mut target = if *fullscreen {
                         screen
                     } else if *fullscreen_within_gaps {
                         Self::apply_outer_gaps(screen, gaps)
                     } else {
                         rect
                     };
+                    if let Some(constraint) = self.window_constraints.get(w) {
+                        if !constraint.is_resizable {
+                            let constrained_size = CGSize::new(
+                                constraint.size.width.min(target.size.width),
+                                constraint.size.height.min(target.size.height),
+                            );
+                            target = CGRect::new(target.origin, constrained_size);
+                        }
+                    }
                     out.push((*w, target));
                 }
             }
@@ -414,19 +433,85 @@ impl BspLayoutSystem {
                     let gap = gaps.inner.horizontal as f64;
                     let total = rect.size.width;
                     let available = (total - gap).max(0.0);
-                    let first_w_f = available * (*ratio as f64);
-                    let first_w = first_w_f.max(0.0);
-                    let second_w = (available - first_w).max(0.0);
+                    let children: Vec<_> = node.children(&self.tree.map).collect();
+                    let first = children.get(0).copied();
+                    let second = children.get(1).copied();
+
+                    let mut first_w = (available * (*ratio as f64)).max(0.0);
+                    let mut second_w = (available - first_w).max(0.0);
+
+                    if let Some(child) = first {
+                        if let Some(constraint) = self.constraint_for_node(child) {
+                            if !constraint.is_resizable {
+                                first_w = constraint.size.width.min(available);
+                            }
+                        }
+                    }
+                    if let Some(child) = second {
+                        if let Some(constraint) = self.constraint_for_node(child) {
+                            if !constraint.is_resizable {
+                                second_w = constraint.size.width.min(available);
+                            }
+                        }
+                    }
+
+                    let mut lengths = [first_w, second_w];
+                    let resizable_indices: Vec<usize> = children
+                        .iter()
+                        .enumerate()
+                        .filter(|(_, child)| {
+                            self.constraint_for_node(**child)
+                                .map(|c| c.is_resizable)
+                                .unwrap_or(true)
+                        })
+                        .map(|(idx, _)| idx)
+                        .collect();
+
+                    let mut total_len: f64 = lengths.iter().sum();
+                    if total_len > available && !resizable_indices.is_empty() {
+                        let mut overflow = total_len - available;
+                        while overflow > 0.0 {
+                            let share = overflow / resizable_indices.len() as f64;
+                            let mut reduced = 0.0;
+                            for &i in &resizable_indices {
+                                let take = lengths[i].min(share);
+                                lengths[i] -= take;
+                                reduced += take;
+                            }
+                            if reduced == 0.0 {
+                                break;
+                            }
+                            total_len -= reduced;
+                            overflow = (total_len - available).max(0.0);
+                        }
+                    } else if total_len > available && resizable_indices.is_empty() && total_len > 0.0 {
+                        let scale = available / total_len;
+                        for len in &mut lengths {
+                            *len *= scale;
+                        }
+                        total_len = available;
+                    }
+
+                    if total_len < available && !resizable_indices.is_empty() {
+                        let extra = available - total_len;
+                        let share = extra / resizable_indices.len() as f64;
+                        for &i in &resizable_indices {
+                            lengths[i] += share;
+                        }
+                    }
+
+                    first_w = lengths[0].max(0.0);
+                    second_w = lengths[1].max(0.0);
+
                     let r1 = CGRect::new(rect.origin, CGSize::new(first_w, rect.size.height));
                     let r2 = CGRect::new(
                         CGPoint::new(rect.origin.x + first_w + gap, rect.origin.y),
                         CGSize::new(second_w, rect.size.height),
                     );
-                    let mut it = node.children(&self.tree.map);
-                    if let Some(first) = it.next() {
+                    if let Some(first) = first {
                         self.calculate_layout_recursive(first, r1, screen, gaps, out);
                     }
-                    if let Some(second) = it.next() {
+                    if let Some(second) = second {
                         self.calculate_layout_recursive(second, r2, screen, gaps, out);
                     }
                 }
@@ -434,19 +519,85 @@ impl BspLayoutSystem {
                     let gap = gaps.inner.vertical as f64;
                     let total = rect.size.height;
                     let available = (total - gap).max(0.0);
-                    let first_h_f = available * (*ratio as f64);
-                    let first_h = first_h_f.max(0.0);
-                    let second_h = (available - first_h).max(0.0);
+                    let children: Vec<_> = node.children(&self.tree.map).collect();
+                    let first = children.get(0).copied();
+                    let second = children.get(1).copied();
+
+                    let mut first_h = (available * (*ratio as f64)).max(0.0);
+                    let mut second_h = (available - first_h).max(0.0);
+
+                    if let Some(child) = first {
+                        if let Some(constraint) = self.constraint_for_node(child) {
+                            if !constraint.is_resizable {
+                                first_h = constraint.size.height.min(available);
+                            }
+                        }
+                    }
+                    if let Some(child) = second {
+                        if let Some(constraint) = self.constraint_for_node(child) {
+                            if !constraint.is_resizable {
+                                second_h = constraint.size.height.min(available);
+                            }
+                        }
+                    }
+
+                    let mut lengths = [first_h, second_h];
+                    let resizable_indices: Vec<usize> = children
+                        .iter()
+                        .enumerate()
+                        .filter(|(_, child)| {
+                            self.constraint_for_node(**child)
+                                .map(|c| c.is_resizable)
+                                .unwrap_or(true)
+                        })
+                        .map(|(idx, _)| idx)
+                        .collect();
+
+                    let mut total_len: f64 = lengths.iter().sum();
+                    if total_len > available && !resizable_indices.is_empty() {
+                        let mut overflow = total_len - available;
+                        while overflow > 0.0 {
+                            let share = overflow / resizable_indices.len() as f64;
+                            let mut reduced = 0.0;
+                            for &i in &resizable_indices {
+                                let take = lengths[i].min(share);
+                                lengths[i] -= take;
+                                reduced += take;
+                            }
+                            if reduced == 0.0 {
+                                break;
+                            }
+                            total_len -= reduced;
+                            overflow = (total_len - available).max(0.0);
+                        }
+                    } else if total_len > available && resizable_indices.is_empty() && total_len > 0.0 {
+                        let scale = available / total_len;
+                        for len in &mut lengths {
+                            *len *= scale;
+                        }
+                        total_len = available;
+                    }
+
+                    if total_len < available && !resizable_indices.is_empty() {
+                        let extra = available - total_len;
+                        let share = extra / resizable_indices.len() as f64;
+                        for &i in &resizable_indices {
+                            lengths[i] += share;
+                        }
+                    }
+
+                    first_h = lengths[0].max(0.0);
+                    second_h = lengths[1].max(0.0);
+
                     let r1 = CGRect::new(rect.origin, CGSize::new(rect.size.width, first_h));
                     let r2 = CGRect::new(
                         CGPoint::new(rect.origin.x, rect.origin.y + first_h + gap),
                         CGSize::new(rect.size.width, second_h),
                     );
-                    let mut it = node.children(&self.tree.map);
-                    if let Some(first) = it.next() {
+                    if let Some(first) = first {
                         self.calculate_layout_recursive(first, r1, screen, gaps, out);
                     }
-                    if let Some(second) = it.next() {
+                    if let Some(second) = second {
                         self.calculate_layout_recursive(second, r2, screen, gaps, out);
                     }
                 }
@@ -564,6 +715,11 @@ impl LayoutSystem for BspLayoutSystem {
         }
     }
 
+    fn set_window_constraints(&mut self, constraints: &HashMap<WindowId, WindowConstraint>) {
+        self.window_constraints.clear();
+        self.window_constraints.extend(constraints.iter().map(|(k, v)| (*k, *v)));
+    }
+
     fn draw_tree(&self, layout: LayoutId) -> String {
         fn write_node(this: &BspLayoutSystem, node: NodeId, out: &mut String, indent: usize) {
             for _ in 0..indent {
@@ -1103,6 +1259,16 @@ impl LayoutSystem for BspLayoutSystem {
     }
 
     fn resize_selection_by(&mut self, layout: LayoutId, amount: f64) {
+        if let Some(wid) = self.selected_window(layout) {
+            if self
+                .window_constraints
+                .get(&wid)
+                .map(|c| !c.is_resizable)
+                .unwrap_or(false)
+            {
+                return;
+            }
+        }
         let sel_snapshot = self.selection_of_layout(layout);
         let Some(mut node) = sel_snapshot else {
             return;
diff --git a/src/layout_engine/systems/traditional.rs b/src/layout_engine/systems/traditional.rs
index 28227b9..39ac251 100644
--- a/src/layout_engine/systems/traditional.rs
+++ b/src/layout_engine/systems/traditional.rs
@@ -3,9 +3,10 @@ use serde::{Deserialize, Serialize};
 use tracing::warn;
 
 use crate::actor::app::{WindowId, pid_t};
+use crate::common::collections::HashMap;
 use crate::layout_engine::systems::LayoutSystem;
 use crate::layout_engine::utils::compute_tiling_area;
-use crate::layout_engine::{Direction, LayoutId, LayoutKind, Orientation};
+use crate::layout_engine::{Direction, LayoutId, LayoutKind, Orientation, WindowConstraint};
 use crate::model::selection::*;
 use crate::model::tree::{self, NodeId, NodeMap, OwnedNode, Tree};
 use crate::sys::geometry::Round;
@@ -377,6 +378,10 @@ impl LayoutSystem for TraditionalLayoutSystem {
         self.layout_roots.remove(layout).unwrap().remove(&mut self.tree)
     }
 
+    fn set_window_constraints(&mut self, constraints: &HashMap<WindowId, WindowConstraint>) {
+        self.tree.data.layout.set_constraints(constraints);
+    }
+
     fn draw_tree(&self, layout: LayoutId) -> String {
         let tree = self.get_ascii_tree(self.root(layout));
         let mut out = String::new();
@@ -900,6 +905,19 @@ impl LayoutSystem for TraditionalLayoutSystem {
 
     fn resize_selection_by(&mut self, layout: LayoutId, amount: f64) {
         let selection = self.selection(layout);
+        if let Some(wid) = self.window_at(selection) {
+            if self
+                .tree
+                .data
+                .layout
+                .constraints
+                .get(&wid)
+                .map(|c| !c.is_resizable)
+                .unwrap_or(false)
+            {
+                return;
+            }
+        }
         if let Some(_focused_window) = self.window_at(selection) {
             let candidates = selection
                 .ancestors(self.map())
@@ -1945,6 +1963,8 @@ impl StackLayoutResult {
 #[derive(Default, Serialize, Deserialize)]
 struct Layout {
     info: slotmap::SecondaryMap<NodeId, LayoutInfo>,
+    #[serde(skip)]
+    constraints: HashMap<WindowId, WindowConstraint>,
 }
 
 #[allow(unused)]
@@ -1962,6 +1982,11 @@ struct LayoutInfo {
 }
 
 impl Layout {
+    fn set_constraints(&mut self, constraints: &HashMap<WindowId, WindowConstraint>) {
+        self.constraints.clear();
+        self.constraints.extend(constraints.iter().map(|(k, v)| (*k, *v)));
+    }
+
     fn handle_event(&mut self, map: &NodeMap, event: TreeEvent) {
         match event {
             TreeEvent::AddedToForest(node) => {
@@ -2242,14 +2267,80 @@ impl Layout {
         } else {
             (axis_len - total_gap).max(0.0)
         };
+        let mut lengths: Vec<f64> = Vec::with_capacity(children.len());
+        for &child in &children {
+            let ratio = f64::from(self.info[child].size) / f64::from(total);
+            lengths.push((usable_axis * ratio).max(0.0));
+        }
+
+        let mut total_len: f64 = lengths.iter().sum();
+        for (idx, &child) in children.iter().enumerate() {
+            let constraint = window.at(child).and_then(|wid| self.constraints.get(&wid));
+            if let Some(constraint) = constraint {
+                if !constraint.is_resizable {
+                    let required = if horizontal {
+                        constraint.size.width
+                    } else {
+                        constraint.size.height
+                    };
+                    lengths[idx] = required.min(usable_axis);
+                }
+            }
+        }
+
+        let resizable_indices: Vec<usize> = children
+            .iter()
+            .enumerate()
+            .filter(|(_, child)| {
+                window
+                    .at(**child)
+                    .and_then(|wid| self.constraints.get(&wid))
+                    .map(|c| c.is_resizable)
+                    .unwrap_or(true)
+            })
+            .map(|(i, _)| i)
+            .collect();
+
+        total_len = lengths.iter().sum();
+        if total_len > usable_axis && !resizable_indices.is_empty() {
+            let mut overflow = total_len - usable_axis;
+            while overflow > 0.0 {
+                let share = overflow / resizable_indices.len() as f64;
+                let mut reduced = 0.0;
+                for &i in &resizable_indices {
+                    let take = lengths[i].min(share);
+                    lengths[i] -= take;
+                    reduced += take;
+                }
+                if reduced == 0.0 {
+                    break;
+                }
+                total_len -= reduced;
+                overflow = (total_len - usable_axis).max(0.0);
+            }
+        } else if total_len > usable_axis && resizable_indices.is_empty() && total_len > 0.0 {
+            let scale = usable_axis / total_len;
+            for len in &mut lengths {
+                *len *= scale;
+            }
+            total_len = usable_axis;
+        }
+
+        if total_len < usable_axis && !resizable_indices.is_empty() {
+            let extra = usable_axis - total_len;
+            let share = extra / resizable_indices.len() as f64;
+            for &i in &resizable_indices {
+                lengths[i] += share;
+            }
+        }
+
         let mut offset = if horizontal {
             rect.origin.x
         } else {
             rect.origin.y
         };
         for (i, &child) in children.iter().enumerate() {
-            let ratio = f64::from(self.info[child].size) / f64::from(total);
-            let seg_len = usable_axis * ratio;
+            let seg_len = lengths[i];
             let child_rect = if horizontal {
                 CGRect {
                     origin: CGPoint { x: offset, y: rect.origin.y },
diff --git a/src/sys/app.rs b/src/sys/app.rs
index 050fbe8..8c721dc 100644
--- a/src/sys/app.rs
+++ b/src/sys/app.rs
@@ -421,6 +421,8 @@ pub struct WindowInfo {
     pub is_root: bool,
     #[serde(default)]
     pub is_minimized: bool,
+    #[serde(default)]
+    pub is_resizable: bool,
     pub title: String,
     #[serde(with = "CGRectDef")]
     pub frame: CGRect,
@@ -443,6 +445,7 @@ impl WindowInfo {
 
         let ax_role = Some(role.clone());
         let ax_subrole = Some(subrole.clone());
+        let is_resizable = element.is_settable("AXSize").unwrap_or(false);
 
         let mut server_info = server_info_hint;
         let id = server_info
@@ -465,6 +468,7 @@ impl WindowInfo {
             is_standard,
             is_root: true,
             is_minimized,
+            is_resizable,
             title: element.title().unwrap_or_default(),
             frame,
             sys_id: id,
diff --git a/src/sys/skylight.rs b/src/sys/skylight.rs
index e478c28..4b6d466 100644
--- a/src/sys/skylight.rs
+++ b/src/sys/skylight.rs
@@ -10,7 +10,7 @@ use bitflags::bitflags;
 use num_enum::{IntoPrimitive, TryFromPrimitive};
 use objc2_application_services::{AXError, AXUIElement};
 use objc2_core_foundation::{
-    CFArray, CFData, CFDictionary, CFNumber, CFString, CFType, CGPoint, CGRect,
+    CFArray, CFData, CFDictionary, CFNumber, CFString, CFType, CGPoint, CGRect, CGSize,
 };
 use objc2_core_graphics::{CGContext, CGError, CGImage, CGWindowID};
 use objc2_foundation::NSArray;
@@ -294,6 +294,13 @@ unsafe extern "C" {
     pub fn SLSWindowIteratorGetAttachedWindowCount(iterator: *mut CFType) -> c_int;
     pub fn SLSWindowIteratorGetPID(iterator: *mut CFType) -> c_int;
     pub fn SLSWindowIteratorGetBounds(iterator: *mut CFType) -> CGRect;
+    pub fn SLSWindowIteratorGetConstraints(
+        iterator: *mut CFType,
+        out_min: *mut CGSize,
+        out_max: *mut CGSize,
+        out_current: *mut CGSize,
+        out_unknown: *mut CGSize,
+    );
 
     pub fn SLSCopySpacesForWindows(
         cid: cid_t,
diff --git a/src/sys/window_server.rs b/src/sys/window_server.rs
index 29abe08..d119293 100644
--- a/src/sys/window_server.rs
+++ b/src/sys/window_server.rs
@@ -76,6 +76,15 @@ pub struct WindowQuery {
     iter: *mut CFType,
 }
 
+#[derive(Debug, Clone, Copy)]
+pub struct WindowIteratorConstraints {
+    pub min: CGSize,
+    pub max: CGSize,
+    pub current: CGSize,
+    pub tags: u64,
+    pub has_dynamic_size: bool,
+}
+
 impl WindowQuery {
     pub fn new(ids: &[WindowServerId]) -> Option<Self> {
         if ids.is_empty() {
@@ -136,6 +145,35 @@ impl WindowQuery {
     #[inline]
     #[allow(dead_code)]
     pub fn attributes(&self) -> u64 { unsafe { SLSWindowIteratorGetAttributes(self.iter) } }
+
+    pub fn constraints(&self) -> WindowIteratorConstraints {
+        let mut min = CGSize::new(0.0, 0.0);
+        let mut max = CGSize::new(0.0, 0.0);
+        let mut current = CGSize::new(0.0, 0.0);
+        let mut unknown = CGSize::new(0.0, 0.0);
+        let tags = self.tags();
+        unsafe {
+            SLSWindowIteratorGetConstraints(
+                self.iter,
+                &mut min,
+                &mut max,
+                &mut current,
+                &mut unknown,
+            );
+        }
+        // STEP 2: Check if window has aspect ratio constraint
+        // But first: tag bits 56-57 indicate windows whose current_size is dynamic (terminals, Finder, etc.)
+        // For these windows, current_size is NOT a meaningful constraint
+        let has_dynamic_size = (tags & 0x0300_0000_0000_0000u64) != 0;
+
+        WindowIteratorConstraints {
+            min,
+            max,
+            current,
+            tags,
+            has_dynamic_size,
+        }
+    }
 }
 
 impl Drop for WindowQuery {
@@ -329,6 +367,12 @@ pub fn get_window(id: WindowServerId) -> Option<WindowServerInfo> {
     (ws.len() == 1).then(|| ws.remove(0))
 }
 
+pub fn window_constraints(id: WindowServerId) -> Option<WindowIteratorConstraints> {
+    let query = WindowQuery::new(&[id])?;
+    query.advance()?;
+    Some(query.constraints())
+}
+
 fn get_num(dict: &CFDictionary<CFString, CFType>, key: &'static CFString) -> Option<i64> {
     dict.get(key)?.downcast::<CFNumber>().ok()?.as_i64()
 }
</details>

**Comment by brianwk** [comment]
@acsandmann same with the patch, the window gets wider in rift's state and the gap returns when I join the windows.

**Comment by acsandmann** [comment]
> [@acsandmann](https://github.com/acsandmann) same with the patch, the window gets wider in rift's state and the gap returns when I join the windows.

could you send a video reproducing?

**Comment by brianwk** [comment]
@acsandmann yeah give me a sec

**Comment by acsandmann** [comment]
> @acsandmann yeah give me a sec

also make sure you are using the latest patch i edited it a few times

**Comment by brianwk** [comment]
@acsandmann i just applied it 8 mins ago
compared hashes, they match

i need to crop the video it's too big for GH

**Comment by brianwk** [comment]
It keeps saying failed to upload. i uploaded to imur... https://imgur.com/a/Fz9cKwk

**Comment by brianwk** [comment]
Then if I do a resize decrease on the Simulator window the gap will lessen but obviously resizing can't fully remove it. Also when I resize it the Simulator window doesn't actually resize at all unless I do it like 6 times or more.

**Comment by brianwk** [comment]
Was finally able to upload, had to use my office connection VPN....

https://github.com/user-attachments/assets/cb3ea241-d5ea-49b4-a049-d9650bd3bb95

First frame tiled perfectly, that is how Rift did it I did not manually do anything and I restarted Rift before recording.

**Comment by acsandmann** [comment]
hmm thats really weird.. i literally added code to account for this in the latest revision of the patch. will have to see

**Comment by brianwk** [comment]
@acsandmann Good news is the patch you gave me seems to fix the Zen Browser issue...

Simulator was tiling BEFORE I applied the patch you gave me. It only messed up once I joined the windows.

Join bug doesn't effect Zen Browser.

**Comment by brianwk** [comment]
Not sure if its the patch you gave me or the latest main, but focus follows mouse doesn't work.

**Comment by acsandmann** [comment]
cant reproduce any of these. maybe try this patch... 

[x.patch](https://github.com/user-attachments/files/24094308/x.patch)

**Comment by brianwk** [comment]
SImulator with join:
```
  {
    "bundle_id": "Simulator",
    "frame": {
      "origin": {
        "x": 5.0,
        "y": 37.0
      },
      "size": {
        "height": 1075.0,
        "width": 854.0
      }
    },
    "id": {
      "idx": 132,
      "pid": 606
    },
    "is_floating": false,
    "is_focused": false,
    "title": "iPhone 16 Pro Max – iOS 18.5",
    "window_server_id": 132
  },
```

Simulator without joined windows beside:
```
﻿﻿﻿﻿﻿  {
    "bundle_id": "Simulator",
    "frame": {
      "origin": {
        "x": 5.0,
        "y": 37.0
      },
      "size": {
        "height": 1075.0,
        "width": 422.0
      }
    },
    "id": {
      "idx": 132,
      "pid": 606
    },
    "is_floating": false,
    "is_focused": false,
    "title": "iPhone 16 Pro Max – iOS 18.5",
    "window_server_id": 132
  },
```

Size of the window doubles in rift when I join the windows beside it.

Latest patch fixes focus follows mouse.

**Comment by brianwk** [comment]
The window is not 800px wide. It's 422px. This is screenshot of just joining the wezterm windows besides it together and that's the only action i took.

<img width="1728" height="1117" alt="Image" src="https://github.com/user-attachments/assets/0bac6a69-b260-45e1-92e2-782b33906520" />

Good news is Zen Browser didn't regress and it's still tiling correctly.... And it also doesn't remain hidden when I go back into the workspace. 

Are you using Sequoia or Tahoe?

BTW....If I unjoin the windows then they all tile correctly.

Do you think it has something to do with the fact that the Simulator is executed from within the WezTerm window or something?

**Comment by acsandmann** [comment]
> The window is not 800px wide. It's 422px. This is screenshot of just joining the wezterm windows besides it together and that's the only action i took.
> 
> <img alt="Image" width="1728" height="1117" src="https://private-user-images.githubusercontent.com/6813130/525200600-0bac6a69-b260-45e1-92e2-782b33906520.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjU0NjI3MzgsIm5iZiI6MTc2NTQ2MjQzOCwicGF0aCI6Ii82ODEzMTMwLzUyNTIwMDYwMC0wYmFjNmE2OS1iMjYwLTQ1ZTEtOTJlMi03ODJiMzM5MDY1MjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTEyMTFUMTQxMzU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTQ5OTcxZTcxNWQ2MzQ1MzY4ZTEwZDhiOWQ1YmQ1MjRlM2ViZTdjYTliNWU3ZGUwOGQ0ODBjZTBkMzJmZDQyMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.TTRyxtf7pwskYUgtzZP61CtRPrnymP4ku0Ccxx_wLTM">
> Good news is Zen Browser didn't regress and it's still tiling correctly.... And it also doesn't remain hidden when I go back into the workspace.
> 
> Are you using Sequoia or Tahoe?
> 
> BTW....If I unjoin the windows then they all tile correctly.
> 
> Do you think it has something to do with the fact that the Simulator is executed from within the WezTerm window or something?

Oohhh maybe it has something to do with the fact it comes from wezterm. ive been testing it by just launching simulator... i wonder if it isnt properly setting constraints or something.

**Comment by brianwk** [comment]
@acsandmann that's the only thing i can think of, it gets launched using Expo from WezTerm. It's also all automated using LUA in WezTerm.

Are you launching it from XCode?

**Comment by acsandmann** [comment]
see if this fixes it(windows being untiled after laptop wakes with less displays than how much it had when it woke).. 
```patch
diff --git a/src/actor/reactor/events/space.rs b/src/actor/reactor/events/space.rs
index 34981e5..e0b1c48 100644
--- a/src/actor/reactor/events/space.rs
+++ b/src/actor/reactor/events/space.rs
@@ -228,9 +228,6 @@ impl SpaceEventHandler {
                 .collect();
             reactor.update_screen_space_map();
             reactor.set_active_spaces(&spaces);
-            // Do not remap layout state across reconnects; new space ids can churn and
-            // remapping has caused windows to oscillate. Keep existing state and only
-            // update the screen→space mapping.
             reactor.reconcile_spaces_with_display_history(&spaces, false);
             if let Some(info) = ws_info_opt.take() {
                 reactor.finalize_space_change(&spaces, info);
@@ -258,11 +255,8 @@ impl SpaceEventHandler {
         if reactor.pending_space_change_manager.topology_relayout_pending
             && spaces.len() != reactor.space_manager.screens.len()
         {
-            println!(
-                "[rift][space_changed] drop mismatch during topology change (screens={}, spaces_len={})",
-                reactor.space_manager.screens.len(),
-                spaces.len()
-            );
+            reactor.pending_space_change_manager.pending_space_change =
+                Some(PendingSpaceChange { spaces, ws_info });
             return;
         }
         // Also drop any space update that reports more spaces than screens; these are
@@ -306,9 +300,12 @@ impl SpaceEventHandler {
                 reactor.space_manager.screens.len(),
                 spaces.len()
             );
+            reactor.pending_space_change_manager.pending_space_change =
+                Some(PendingSpaceChange { spaces, ws_info });
             return;
         }
-        reactor.reconcile_spaces_with_display_history(&spaces, false);
+        let allow_remap = reactor.pending_space_change_manager.topology_relayout_pending;
+        reactor.reconcile_spaces_with_display_history(&spaces, allow_remap);
         info!("space changed");
         reactor.set_screen_spaces(&spaces);
         reactor.finalize_space_change(&spaces, ws_info);
@@ -322,6 +319,7 @@ impl SpaceEventHandler {
                 warn!(error = ?e, "Layout update failed after topology change");
             }
         }
+        reactor.try_apply_pending_space_change();
     }
 
     pub fn handle_mission_control_native_entered(reactor: &mut Reactor) {
diff --git a/src/actor/reactor/events/system.rs b/src/actor/reactor/events/system.rs
index dd34af3..c6c479a 100644
--- a/src/actor/reactor/events/system.rs
+++ b/src/actor/reactor/events/system.rs
@@ -1,4 +1,4 @@
-use tracing::debug;
+use tracing::{debug, warn};
 
 use crate::actor::app::WindowId;
 use crate::actor::raise_manager;
@@ -35,10 +35,18 @@ impl SystemEventHandler {
     }
 
     pub fn handle_system_woke(reactor: &mut Reactor) {
+        // On wake, window server can reshuffle windows or drop visibility state.
+        // Force a refresh + layout to restore the desired placement even if no
+        // display-change notification fires.
         let ids: Vec<u32> =
             reactor.window_manager.window_ids.keys().map(|wsid| wsid.as_u32()).collect();
         crate::sys::window_notify::update_window_notifications(&ids);
         reactor.notification_manager.last_sls_notification_ids = ids;
+        reactor.force_refresh_all_windows();
+        reactor.check_for_new_windows();
+        if let Err(err) = reactor.update_layout(false, false) {
+            warn!(?err, "Layout update failed after wake");
+        }
     }
 
     pub fn handle_raise_completed(reactor: &mut Reactor, window_id: WindowId, sequence_id: u64) {
diff --git a/src/actor/wm_controller.rs b/src/actor/wm_controller.rs
index cab492d..e0e6e6c 100644
--- a/src/actor/wm_controller.rs
+++ b/src/actor/wm_controller.rs
@@ -349,6 +349,10 @@ impl WmController {
                         converter,
                     ));
                 }
+                // Ensure the reactor receives a SpaceChanged event even if macOS
+                // doesn't emit a standalone space notification (common on wake when
+                // a display was detached).
+                self.events_tx.send(Event::SpaceChanged(active_spaces, self.get_windows()));
             }
             SpaceChanged(spaces) => {
                 self.handle_space_changed(spaces.clone());

```


@brianwk i am launching it through spotlight so it isnt connected to xcode ot terminal or anything

**Comment by brianwk** [comment]
@acsandmann i applied the patch, i'll let you know when I get home the results...

**Comment by brianwk** [comment]
@acsandmann 

Crap, forgot to post this comment earlier: Seems like the Simulator doesn't tile correctly, it's just some fluke that it tiled correctly on the builtin MacBook display, when I came to work today, restarted Rift, the size shows as doubled again since the window has more room on this display:

```
❯ rift-cli query windows|jq
[
  {
    "bundle_id": "Simulator",
    "frame": {
      "origin": {
        "x": 20.0,
        "y": 35.0
      },
      "size": {
        "height": 1385.0,
        "width": 828.0
      }
    },
    "id": {
      "idx": 132,
      "pid": 606
    },
    "is_floating": false,
    "is_focused": false,
    "title": "iPhone 16 Pro Max – iOS 18.5",
    "window_server_id": 132
  },
```

**Comment by brianwk** [comment]
@acsandmann The patch fixes the issue when the Mac wakes on sleep after having an external display connected.

However,  I'm still having issues with directional focus with external display.

**Comment by acsandmann** [comment]
> [@acsandmann](https://github.com/acsandmann) The patch fixes the issue when the Mac wakes on sleep after having an external display connected.
> 
> However, I'm still having issues with directional focus with external display.

what do you mean by directional focus? like focusing windows or moving windows to displays or..

**Comment by brianwk** [comment]
@acsandmann Moving focus from one window to the other. It's cursed when you have multiple displays connected at times. Like the focus won't go left or right, and will be stuck on the window on the wrong display. This is an issue because the focus goes to the next screen and then you can't go back to the previous screen.

Single display it always works great.
